# Generated by Django 4.0.5 on 2022-06-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Image_Type',
        ),
        migrations.AddField(
            model_name='found',
            name='Color',
            field=models.CharField(help_text='pet Color', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lost',
            name='Color',
            field=models.CharField(help_text='pet Color', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='found',
            name='Name',
            field=models.CharField(help_text='pet name', max_length=100),
        ),
        migrations.AlterField(
            model_name='found',
            name='Phone',
            field=models.CharField(help_text='phone', max_length=100),
        ),
        migrations.AlterField(
            model_name='lost',
            name='Name',
            field=models.CharField(help_text='pet name', max_length=100),
        ),
        migrations.AlterField(
            model_name='lost',
            name='Phone',
            field=models.CharField(help_text='phone', max_length=100),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
