# Generated by Django 4.0.5 on 2022-06-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets_App', '0002_remove_image_image_type_found_color_lost_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='Characteristic',
            field=models.CharField(help_text='characteristic', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lost',
            name='Characteristic',
            field=models.CharField(help_text='characteristic', max_length=500, null=True),
        ),
    ]
